###################
# Install Package #
###################
remove.packages("rmarkdown")
install.packages("https://cran.r-project.org/src/contrib/Archive/rmarkdown/rmarkdown_2.5.tar.gz", repos=NULL, type='source')
install.packages("flexdashboard")
install.packages("shiny")
install.packages("tidyverse")
install.packages("DT")
install.packages("psych")
install.packages("skimr")
install.packages("gmodels")
install.packages("rstatix")
install.packages("corrr")
install.packages("tigerstats")
install.packages("nortest")
install.packages("car")
install.packages("Rmisc")
install.packages("gplots")
install.packages("lsr")
install.packages("RVAideMemoire")
install.packages("GPArotation")
install.packages("yacca")
install.packages("candisc")
install.packages("irr")
