---
title: "Canonical Correlation Analysis"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    logo: R_logo.png
runtime: shiny
---

```{r}
library(flexdashboard)
library(tidyverse)
library(DT)
library(yacca)
library(ggthemes)


setwd("~/R-aplikacije/Data")

data <- read.table(file.choose(),                  
                   header = TRUE,                      
                   dec = ",",                          
                   sep = ";",                          
                   stringsAsFactors = TRUE,
                   row.names = 1)

my_data <- data %>% select_if(is.numeric)
m <- ncol(my_data)
n <- nrow(my_data)
fnames <- paste0("CF", 1:m)

```

Data
=======================================================================
Column {data-width=1000}
-----------------------------------------------------------------------
### Data
```{r}
DT::datatable(data, style = 'bootstrap', 
              filter = 'top', 
              extensions = 'Buttons', 
              options = list(pageLength = n, dom = 'Brti', buttons = c('copy','csv', 'excel')))
```

Canonical Analysis
=======================================================================
Column {data-width=1000}
-----------------------------------------------------------------------
### Canonical Analysis

```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
          checkboxGroupInput("B1", "Select Variables - First Set:",
                            names(my_data), selected = names(my_data[1:(m-3)])),
          
          checkboxGroupInput("B2", "Select Variables - Second Set:",
                            names(my_data), selected = names(my_data[(m-2):m]))
        ),
        mainPanel(
          tabsetPanel(
            tabPanel("Canonical Analysis Results", br(),
                     dataTableOutput("RC"),
                     hr(),
                     h5("Factor Structure - First Set"),
                     dataTableOutput("F1"),
                     hr(),
                     h5("Factor Structure - Second Set"),
                     dataTableOutput("F2"),
                     hr(),
                     h5("Graph Factor Structure - First Set"),
                     plotOutput("GFF1"),
                     hr(),
                     h5("Graph Factor Structure - Second Set"),
                     plotOutput("GFF2"),
                     ),
            tabPanel("Canonical Scores - First Set", br(),
                     dataTableOutput("CF1")),
            tabPanel("Canonical Scores - Second Set", br(),
                     dataTableOutput("CF2"))
            )
        )
    ),

server <- function(input, output, session) {
    
     selectedData1 <- reactive({my_data[, input$B1]})
     selectedData2 <- reactive({my_data[, input$B2]})
    
      output$RC <- renderDataTable({
        B1 <- selectedData1()
        B2 <- selectedData2()
        m1 <- ncol(B1)
        m2 <- ncol(B2)
        if (m1<=m2) {k=m1} else {k=m2}
        if (m1>=m2) {rcca<- cca (B1, B2, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        else {rcca<- cca (B2, B1, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        p <- pchisq(rcca$chisq, rcca$df, lower.tail = FALSE)
        RC <- cbind.data.frame(fnames[1:k], round(rcca$corr, digits = 3), round(rcca$chisq, digits = 3), rcca$df, round(p, digits = 3))
        Rc <- RC[c(1,2,3,4,5)]
        colnames(RC) <- c("CF", "Rc", "Chi-sq.","df", "p-level")

        RC %>% DT::datatable (rownames=FALSE, 
                               style = 'bootstrap', 
                               extensions = 'Buttons', 
                               options = list(pageLength = k, dom = 'Bt', buttons = c('copy'))) %>% 
                               formatStyle("p-level", color = styleInterval(c(0.05), c('red', 'black')))
      })
      
      cbind
      output$F1 <- renderDataTable({
        B1 <- selectedData1()
        B2 <- selectedData2()
        m1 <- ncol(B1)
        m2 <- ncol(B2)
        if (m1<=m2) {k=m1} else {k=m2}
        if (m1>=m2) {rcca<- cca (B1, B2, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        else {rcca<- cca (B2, B1, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        if (m1>=m2) {F1 <- round(rcca$xstructcorr, digits = 3)} else {F1 <- round(rcca$ystructcorr, digits = 3)} 
        colnames(F1) <- fnames[1:k]
        F1 %>% DT::datatable (rownames=TRUE, 
                               style = 'bootstrap', 
                               extensions = 'Buttons', 
                               options = list(pageLength = m1, dom = 'Bt',buttons = c('copy')))
      })
      
      output$F2 <- renderDataTable({
        B1 <- selectedData1()
        B2 <- selectedData2()
        m1 <- ncol(B1)
        m2 <- ncol(B2)
        if (m1<=m2) {k=m1} else {k=m2}
        if (m1>=m2) {rcca<- cca (B1, B2, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        else {rcca<- cca (B2, B1, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        if (m1>=m2) {F2 <- round(rcca$ystructcorr, digits = 3)} else {F2 <- round(rcca$xstructcorr, digits = 3)} 
        colnames(F2) <- fnames[1:k]
        F2 %>% DT::datatable (rownames=TRUE, 
                               style = 'bootstrap', 
                               extensions = 'Buttons', 
                               options = list(pageLength = m2, dom = 'Bt',buttons = c('copy')))
      })
      
      output$CF1 <- renderDataTable({
        B1 <- selectedData1()
        B2 <- selectedData2()
        m1 <- ncol(B1)
        m2 <- ncol(B2)
        if (m1<=m2) {k=m1} else {k=m2}
        if (m1>=m2) {rcca<- cca (B1, B2, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        else {rcca<- cca (B2, B1, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        if (m1>=m2) {CF1 <- round(rcca$canvarx, digits = 3)} else {CF1 <- round(rcca$canvary, digits = 3)} 
        colnames(CF1) <- fnames[1:k]
        CF1 %>% DT::datatable (rownames=TRUE, 
                               style = 'bootstrap', 
                               extensions = 'Buttons', 
                               options = list(pageLength = n, dom = 'Bt',buttons = c('copy')))
      })
      
      output$CF2 <- renderDataTable({
        B1 <- selectedData1()
        B2 <- selectedData2()
        m1 <- ncol(B1)
        m2 <- ncol(B2)
        if (m1<=m2) {k=m1} else {k=m2}
        if (m1>=m2) {rcca<- cca (B1, B2, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        else {rcca<- cca (B2, B1, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        if (m1>=m2) {CF2 <- round(rcca$canvary, digits = 3)} else {CF2 <- round(rcca$canvarx, digits = 3)} 
        colnames(CF2) <- fnames[1:k]
        CF2 %>% DT::datatable (rownames=TRUE, 
                               style = 'bootstrap', 
                               extensions = 'Buttons', 
                               options = list(pageLength = n, dom = 'Bt',buttons = c('copy')))
      })
      
      output$GFF1 <- renderPlot({
        B1 <- selectedData1()
        B2 <- selectedData2()
        m1 <- ncol(B1)
        m2 <- ncol(B2)
        if (m1<=m2) {k=m1} else {k=m2}
        if (m1>=m2) {rcca<- cca (B1, B2, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)} 
        else {rcca<- cca (B2, B1, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        nvar1 <- colnames(B1)
        if (m1>=m2) {F1 <- round(rcca$xstructcorr, digits = 3)} else {F1 <- round(rcca$ystructcorr, digits = 3)} 
        Faktori <- fnames[1:k]
        Fac1 <- rep(Faktori, each=m1)
        Var1 <- rep(nvar1, times=k)
        Loa1 <- c()
        for (a in 1:k) {Loa1 <- c(Loa1,F1[,a])}
        CFF1 <- data_frame(Fac1,Var1,Loa1)
     ggplot(data=CFF1, aes(x=Fac1,y=Loa1,fill=Var1)) +
          geom_bar(position ="stack",stat="identity") +
          labs(x ="Canonical factors",y ="Loadings",fill ="Variables",title= "")+
          theme_minimal() + scale_fill_ptol()
      })
      
      output$GFF2 <- renderPlot({
        B1 <- selectedData1()
        B2 <- selectedData2()
        m1 <- ncol(B1)
        m2 <- ncol(B2)
        if (m1<=m2) {k=m1} else {k=m2}
        if (m1>=m2) {rcca<- cca (B1, B2, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)} 
        else {rcca<- cca (B2, B1, xscale = TRUE, yscale = TRUE, standardize.scores = TRUE)}
        nvar2 <- colnames(B2)
        if (m1>=m2) {F2 <- round(rcca$ystructcorr, digits = 3)} else {F2 <- round(rcca$xstructcorr, digits = 3)} 
        Faktori <- fnames[1:k]
        Fac2 <- rep(Faktori, each=m2)
        Var2 <- rep(nvar2, times=k)
        Loa2 <- c()
        for (a in 1:k) {Loa2 <- c(Loa2,F2[,a])}
        CFF2 <- data_frame(Fac2,Var2,Loa2)
     ggplot(data=CFF2, aes(x=Fac2,y=Loa2,fill=Var2)) +
          geom_bar(position ="stack",stat="identity") +
          labs(x ="Canonical factors",y ="Loadings",fill ="Variables",title= "")+
          theme_minimal() + scale_fill_ptol()
      })
      
      
},
shinyApp(ui = ui, server = server)
)
```
