---
title: "Reliability Analysis"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    logo: R_logo.png
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(DT)
library(psych)
```

```{r}

setwd("~/R-aplikacije/Data")

data <- read.table(file.choose(),                  
                   header = TRUE,                      
                   dec = ",",                          
                   sep = ";",                          
                   stringsAsFactors = TRUE,
                   row.names = 1)

test <- data %>% select_if(is.numeric)
n <- nrow(test)                                  
```
Data
=======================================================================
Column {data-width=1000}
-----------------------------------------------------------------------
### Data

```{r}
DT::datatable(data, extensions = 'Buttons', options = list(pageLength = n, dom = 'Bfrtip', buttons = c('copy','csv', 'excel')))
```

Reliability Analysis
=======================================================================
Column {data-width=1000}
-----------------------------------------------------------------------
### Reliability Analysis

```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
         checkboxGroupInput("select_vars", "Select Variables:",
                            names(test), selected = names(test[1:3]))
    
        ),
        mainPanel(
          htmlOutput("alpha"),
          hr(),
          h5("Item Reliability Statistics"),
          dataTableOutput("irs"),
          hr(),
          h5("Condensed Data"),
          dataTableOutput("cd"))
),

server <- function(input, output, session) {
   selectedData <- reactive({test[, input$select_vars]})

  output$alpha <- renderText({
    my_data <- selectedData()
    m <- ncol(my_data)

    X <- as.matrix(my_data)                    
    i <- rep(c(1), times=m)                     
    Xs <- X %*% i                               
    ds <- describe(my_data, type=2)
    svar <- sum(ds[,4]*ds[,4]) 
    varXs <- var(Xs)
    Z <- scale(X)
    Zs <- Z %*% i 
    varZs <- var(Zs)
    k <- principal(X, nfactors=1, scores=TRUE)   
    lamda1 <- k$values[1]     
    R <- cor(X)
    k <- (m*m-m)/2                              
    AIC<- c((sum(R)-m)/2)/k
    Cronbach <- m/(m-1)*(1-svar/varXs)
    SB <- m/(m-1)*(1-m/varZs) 
    KC <- m/(m-1)*(1-1/lamda1)   
    
    paste("Cronbach's alpha =", round(Cronbach, digits = 3), br(),
          "Spearman-Brown alpha =", round(SB, digits = 3), br(),
          "Kaiser-Caffrey alpha =", round(KC, digits = 3), br(),
          "Average interitem correlation =", round(AIC, digits = 3))
    })
  
  output$irs <- renderDataTable({
    my_data <- selectedData()
    m <- ncol(my_data)
    alp <- alpha(my_data)
    is1 <- alp$item.stats
    is2 <- alp$alpha.drop
    is <- cbind.data.frame(is1, is2)
    irs <- is[c(6, 7, 5, 8)]
    colnames(irs) <- c("Mean", "St.dev", "Item-total correlation", "Alpha if deleted")
    irs %>% DT::datatable (rownames = TRUE, 
                          style = 'bootstrap', 
                          extensions = 'Buttons', 
                          options = list(pageLength = m, dom = 'Bt',buttons = c('copy'))) %>% 
                          formatRound(colnames(irs), digits=3)
  })
  
  output$cd <- renderDataTable({
    my_data <- selectedData()
    
    m <- ncol(my_data)
    X <- as.matrix(my_data)
    i <- rep(c(1), times=m) 
    Xs <- X %*% i 
    Xas <- Xs/m                                 
    colnames(Xas) <- c("X-mean")
    Z <- scale(X)
    Zs <- Z %*% i 
    Zas <- Zs/m                                 
    colnames(Zas) <- c("Z-mean")
    k <- principal(X, nfactors=1, scores=TRUE)   
    K1 <- k$scores
    cd <- cbind.data.frame(Xas, Zas, K1)
    cd %>% DT::datatable (rownames = TRUE, 
                          style = 'bootstrap', 
                          extensions = 'Buttons', 
                          options = list(pageLength = n, dom = 'Bt',buttons = c('copy'))) %>% 
                          formatRound(colnames(cd), digits=3)
  })
},
shinyApp(ui = ui, server = server)
)
```


