---
title: "Data Transformation"
output: 
  flexdashboard::flex_dashboard:
    #theme: bootstrap
    #theme: cerulean
    #theme: flatly
    #theme: united
    #theme: simplex
    theme: yeti
    logo: R_logo.png
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)
library(psych)
library(skimr)
```

```{r}
#data <- read.table(file = "UCENICI.csv",
setwd("~/R-aplikacije/Datoteke/CSV")

data <- read.table(file.choose(),                  
                   header = TRUE,                      
                   dec = ",",                          
                   sep = ";",                          
                   stringsAsFactors = TRUE,
                   row.names = 1)
summary <- skim(data)
n <- nrow(data)                                  
m <- ncol(data)
numeric <- data %>% select_if(is.numeric)
#nominal <- data %>% select_if(is.factor)
var_name <- names(data)
var_name_numeric <- names(numeric)
#var_name_nominal <- names(nominal)
```

Z- value
=======================================================================

Column {data-width=10}
-----------------------------------------------------------------------

### Cases

```{r}
valueBox(n)
```

### Variables

```{r}
valueBox(m)
```

### Data

```{r}
valueBox(n*m)
```

Column {data-width=990}
----------------------------------------------------------------------- 

### Z - value

```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
         checkboxGroupInput("select_vars", "Select Variables:",
                            names(numeric), selected = names(numeric)),
        ),
        mainPanel(
          dataTableOutput("z")
          )
),

server <- function(input, output, session) {

  selectedData <- reactive({
    data[, input$select_vars]
  })
    
  output$z <- renderDataTable({
    my_data <- selectedData()
    Z <- round(scale(my_data), digits = 2)
    Z %>% DT::datatable (rownames = TRUE, extensions = 'Buttons', options = list(pageLength = n, dom = 'Bt',buttons = c('copy')))
  })
  
},

shinyApp(ui = ui, server = server)
)
```

T - value
=======================================================================

Column {data-width=10}
-----------------------------------------------------------------------

### Cases

```{r}
valueBox(n)
```

### Variables

```{r}
valueBox(m)
```

### Data

```{r}
valueBox(n*m)
```

Column {data-width=990}
----------------------------------------------------------------------- 

### T - value

```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
         checkboxGroupInput("select_vars", "Select Variables:",
                            names(numeric), selected = names(numeric)),
        ),
        mainPanel(
          dataTableOutput("T")
          )
),

server <- function(input, output, session) {

  selectedData <- reactive({
    data[, input$select_vars]
  })
    
  output$T <- renderDataTable({
    my_data <- selectedData()
    T <- round(scale(my_data), digits = 2)*10+50
    T %>% DT::datatable (rownames = TRUE, extensions = 'Buttons', options = list(pageLength = n, dom = 'Bt',buttons = c('copy')))
  })
  
},

shinyApp(ui = ui, server = server)
)
```

L - value (1-5)
=======================================================================

Column {data-width=10}
-----------------------------------------------------------------------

### Cases

```{r}
valueBox(n)
```

### Variables

```{r}
valueBox(m)
```

### Data

```{r}
valueBox(n*m)
```

Column {data-width=990}
----------------------------------------------------------------------- 

### L - value (1-5)

```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
         checkboxGroupInput("select_vars", "Select Variables:",
                            names(numeric), selected = names(numeric)),
        ),
        mainPanel(
          dataTableOutput("L")
          )
),

server <- function(input, output, session) {

  selectedData <- reactive({
    data[, input$select_vars]
  })
    
  output$L <- renderDataTable({
    my_data <- selectedData()
    L <- round(scale(my_data)*0.833+3, digits = 2)
    L %>% DT::datatable (rownames = TRUE, extensions = 'Buttons', options = list(pageLength = n, dom = 'Bt',buttons = c('copy')))
  })
  
},

shinyApp(ui = ui, server = server)
)
```

Harris Metric
=======================================================================

Column {data-width=10}
-----------------------------------------------------------------------

### Cases

```{r}
valueBox(n)
```

### Variables

```{r}
valueBox(m)
```

### Data

```{r}
valueBox(n*m)
```

Column {data-width=990}
----------------------------------------------------------------------- 

### Harris Metric

```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
         checkboxGroupInput("select_vars", "Select Variables:",
                            names(numeric), selected = names(numeric)),
        ),
        mainPanel(
          dataTableOutput("H")
          )
),

server <- function(input, output, session) {

  selectedData <- reactive({
    data[, input$select_vars]
  })
    
  output$H <- renderDataTable({
    my_data <- selectedData()
    Z <- scale(my_data)
    R <- cor(my_data)
    invR <- solve(R)
    invU2 <- diag(invR)
    invU <- diag(sqrt(invU2))
    H <- round(Z %*% invU, digits = 2)                        
    colnames(H) <- input$select_vars
    H %>% DT::datatable (rownames = TRUE, extensions = 'Buttons', options = list(pageLength = n, dom = 'Bt',buttons = c('copy')))
  })
  
},

shinyApp(ui = ui, server = server)
)
```

Image Metric
=======================================================================

Column {data-width=10}
-----------------------------------------------------------------------

### Cases

```{r}
valueBox(n)
```

### Variables

```{r}
valueBox(m)
```

### Data

```{r}
valueBox(n*m)
```

Column {data-width=990}
----------------------------------------------------------------------- 

### Image Metric

```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
         checkboxGroupInput("select_vars", "Select Variables:",
                            names(numeric), selected = names(numeric)),
        ),
        mainPanel(
          dataTableOutput("IM")
          )
),

server <- function(input, output, session) {

  selectedData <- reactive({
    data[, input$select_vars]
  })
    
  output$IM <- renderDataTable({
    my_data <- selectedData()
    m <- ncol(my_data)
    I <- I <- diag(1, m)
    Z <- scale(my_data)
    R <- cor(my_data)
    invR <- solve(R)
    invU2 <- diag(invR)
    U2 <- solve(diag(invU2))
    IM <- round(Z %*% (I-invR %*% U2), digits = 2)                          
    colnames(IM) <- input$select_vars
    IM %>% DT::datatable (rownames = TRUE, extensions = 'Buttons', options = list(pageLength = n, dom = 'Bt',buttons = c('copy')))
  })
  
},

shinyApp(ui = ui, server = server)
)
```
