---
title: "Analysis of variance (ANOVA)"
output: 
  flexdashboard::flex_dashboard:
    #theme: bootstrap
    #theme: cerulean
    #theme: flatly
    #theme: united
    #theme: simplex
    theme: yeti
    logo: R_logo.png
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)
library(psych)
library(car)
library(Rmisc)
library(gplots)
library(skimr)
```

```{r Učitavanje podataka iz CSV datoteke}
data <- read.table(file.choose(),                  
                   header = TRUE,                      
                   dec = ",",                          
                   sep = ";",                          
                   stringsAsFactors = TRUE,
                   row.names = 1)

#saveRDS(data, file = "my_data.RData") 
#head(data)
```

```{r Selekcija varijabli}
Factor <- data %>% select_if(is.factor)
Dependent <- data %>% select_if(is.numeric)
#Dependent <- data %>% select(ATV:MVIS)
#Factor <- data %>% select(KRAJ, RAZRED, SPOL)
```

```{r}
my_data <- cbind(Factor, Dependent)
k <- ncol(Factor)
m1 <- ncol(Dependent)
n = nrow(my_data)
m = ncol(my_data)
summary <- skim(data)
```

Data
=======================================================================

Column {data-width=10}
-----------------------------------------------------------------------

### Cases

```{r}
valueBox(n)
```

### Variables

```{r}
valueBox(m)
```

### Data

```{r}
valueBox(n*m)
```

Column {data-width=990 .tabset}
-----------------------------------------------------------------------

### Data

```{r}
DT::datatable(data, extensions = 'Buttons', options = list(pageLength = n, dom = 'Bfrtip',buttons = c('copy','csv', 'excel')))
```

### Data Summary

```{r}
summary
```


Descriptive Statistics
=======================================================================

Column {data-width=10}
-----------------------------------------------------------------------

### Cases

```{r}
valueBox(n)
```

### Variables

```{r}
valueBox(m)
```

### Data

```{r}
valueBox(n*m)
```


Column {data-width=990}
-----------------------------------------------------------------------

### Descriptive Statistics

```{r}

shinyApp(

ui <- fluidPage(
        sidebarPanel(
          radioButtons("radio1", 
                       label = "Dependent Variables:",
                       choices = colnames(my_data[k+1:m1])),
           radioButtons("radio2", 
                       label = "Factor:",
                       choices = colnames(my_data[1:k])),
           sliderInput("bins",
                        "Broj razreda:",
                        min = 1,
                        max = 100,
                        value = 7)
          
        ),
        mainPanel(
          h4("Normality Test (Shapiro-Wilk's)"),
          textOutput("shapiro"),
          hr(),
          plotOutput("histogram"),
          hr(),
          h4("Descriptive Statistics"),
          dataTableOutput ("des"),
          hr(),
          h4("Homogeneity of Variances Test (Levene's)*"),
          textOutput ("lev"),
          hr(),
          h4("Box and Whiskers plot"),
          plotOutput("box"),
          hr(),
          h6("*Izvorni Leveneov test homogenosti varijanci računa odstupanja rezultata entiteta od aritmetičke sredine. Brown i Forsythe (1974.) su predložili da se umjesto aritmetičke sredine koristi medijan jer je manje osjetljiv (bolja mjera centralne tendencije) u slučaju asimetričnih distribucija podataka.")
        )
),
server <- function(input, output, session) {

      selectedData1 <- reactive({
        my_data[, input$radio1]
  })
      selectedData2 <- reactive({   
        my_data[, input$radio2]
  })
      
       output$des <- renderDataTable({
        Variables <- selectedData1()
        Factor    <- selectedData2()
        des <-summarySE(my_data,
              measurevar= input$radio1,
              groupvars=c(input$radio2))
        colnames(des) <- c("Groups", "N", "Mean", "St. Dev.", "St. Err.", "Conf. Int.")
        des%>% DT::datatable (rownames = FALSE, extensions = 'Buttons', options = list(pageLength = 100, dom = 'Bt',buttons = c('copy'))) %>% formatRound(c('Mean', 'St. Dev.', 'St. Err.', 'Conf. Int.'), 3)
       })
       
      output$shapiro <- renderText({ 
        w <- selectedData1()
        sw <- shapiro.test(w)
        W <- round(sw$statistic, digits = 3)
        p <- round(sw$p.value, digits = 3)
        paste("W = ", W,", p = ", p)
  })
      output$histogram <- renderPlot({
        x    <- selectedData1()
        mean <- mean(selectedData1())
        sd <- sd(selectedData1())
        ggplot(my_data, aes(x=x)) + 
        geom_histogram(bins=input$bins, color="#ffffff", fill="#5BC0DE") +
        labs(x= input$radio, y = "Frequency") +
        theme_minimal()
  })
   
      output$lev <- renderText({
        Variables <- selectedData1()
        Factor    <- selectedData2()
        lt <- leveneTest(Variables ~ Factor, data = my_data, center=median)
        Fl <- round(lt$`F value`[1], digits = 3)
        pl <- round(lt$`Pr(>F)`[1], digits = 3)
        paste("F = ", Fl,", p = ", pl)
      }) 
       
      output$box <- renderPlot({
        Variables  <- selectedData1()
        Groups     <- selectedData2()
        ggplot(my_data, aes(x=Groups, y=Variables, fill=Groups)) + 
        #geom_violin (color="#ffffff", alpha=0.7) +
        geom_boxplot(color="#000000",outlier.colour="red",outlier.shape=8, outlier.size=4) +
        stat_summary(fun=mean, geom="point", shape=16, size=2, color="#000000") +
        labs(x = input$radio1, y = input$radio2) +
        theme_minimal()
})

},
shinyApp(ui = ui, server = server)
)
```

One-way ANOVA
=======================================================================

Column {data-width=10}
-----------------------------------------------------------------------

### entiteta

```{r}
valueBox(n)
```

### varijabli

```{r}
valueBox(m)
```

### podataka

```{r}
valueBox(n*m)
```

Column {data-width=490}
-----------------------------------------------------------------------
### One-way ANOVA

```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
          radioButtons("radio1", 
                       label = "Dependent Variables:",
                       choices = colnames(my_data[k+1:m1])),
           radioButtons("radio2", 
                       label = "Factor:",
                       choices = colnames(my_data[1:k])),
        ),
        mainPanel(
          h4("One-way ANOVA"),
          dataTableOutput("ANOVA"),
          hr(),hr(),
          h4("Post Hoc Test for Multiple Comparisons (Tukey)"),
          dataTableOutput ("tukey"),
          hr(),
          h4("Mean Plot with 95% Confidence Interval"),
          plotOutput("err"),
          hr(),
          h4("Homogeneity of Variances Test (Levene's)*"),
          textOutput("lev"),
          plotOutput("res"),
          hr(),
          h4("Normality Test (Shapiro-Wilk's)"),
          textOutput("shapiro"),
          plotOutput("qqres"),
          hr(),
          h6("*Izvorni Leveneov test homogenosti varijanci računa odstupanja rezultata entiteta od aritmetičke sredine. Brown i Forsythe (1974.) su predložili da se umjesto aritmetičke sredine koristi medijan jer je manje osjetljiv (bolja mjera centralne tendencije) u slučaju asimetričnih distribucija podataka.")
        )
),
server <- function(input, output, session) {

      selectedData1 <- reactive({
        my_data[, input$radio1]
  })
      selectedData2 <- reactive({   
        my_data[, input$radio2]
  })
      
      output$ANOVA <- renderDataTable({
        Variables <- selectedData1()
        Factor     <- selectedData2()
        res.aov <- aov(Variables ~ Factor, data = my_data)
        anova <- summary(res.aov)
        colnames(anova[[1]]) <- c("df", "Sum Square","Mean Square", "F-value", "p-level")
        anova[[1]] %>% DT::datatable (extensions = 'Buttons', options = list(dom = 'Bt',buttons = c('copy'))) %>% formatRound(c('Sum Square', 'Mean Square', 'F-value', 'p-level'), 3)
    })
       
      output$tukey <- renderDataTable({
        Variables <- selectedData1()
        Factor     <- selectedData2()
        tuk <- TukeyHSD(aov(Variables ~ Factor, data = my_data))
        colnames(tuk[[1]]) <- c("Mean Diff.", "Lower Bound","Upper Bound", "p-level")
        tuk[[1]]%>% DT::datatable (extensions = 'Buttons', options = list(pageLength = 100, dom = 'Bt',buttons = c('copy'))) %>% formatRound(c('Mean Diff.', 'Lower Bound', 'Upper Bound', 'p-level'), 3)
    })
      
       output$err <- renderPlot({
        Variables <- selectedData1()
        Factor <-  selectedData2()
        plotmeans(Variables~Factor, data=my_data, col="red", barwidth=1,
          barcol="black",connect=FALSE, n.label=FALSE, xlab="")
    })

      output$res <- renderPlot({
        Variables <- selectedData1()
        Factor     <- selectedData2()
        res.aov <- aov(Variables ~ Factor, data = my_data)
        plot(res.aov,1)
    })   
     output$qqres <- renderPlot({
        Variables <- selectedData1()
        Factor     <- selectedData2()
        res.aov <- aov(Variables ~ Factor, data = my_data)
        plot(res.aov,2)
    })   
     
      output$lev <- renderText({
        Variables <- selectedData1()
        Factor     <- selectedData2()
        lt <- leveneTest(Variables ~ Factor, data = my_data, center = mean)
        Fl <- round(lt$`F value`[1], digits = 3)
        pl <- round(lt$`Pr(>F)`[1], digits = 3)
        paste("F = ", Fl,", p = ", pl)
    })   
     
     output$shapiro <- renderText({
        Variables <- selectedData1()
        Factor     <- selectedData2()
        res.aov <- aov(Variables ~ Factor, data = my_data)
        res.residuals <- residuals(object = res.aov)
        sw <- shapiro.test(x = res.residuals)   
        W <- round(sw$statistic, digits = 3)
        p <- round(sw$p.value, digits = 3)
        paste("W = ", W,", p = ", p)
    })   
},
shinyApp(ui = ui, server = server)
)

```

Two-Way ANOVA
=======================================================================

Column {data-width=10}
-----------------------------------------------------------------------

### entiteta

```{r}
valueBox(n)
```

### varijabli

```{r}
valueBox(m)
```

### podataka

```{r}
valueBox(n*m)
```

Column {data-width=490}
-----------------------------------------------------------------------
### Two-Way ANOVA

```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
          radioButtons("radio1", 
                       label = "Dependent Variables:",
                       choices = colnames(my_data[k+1:m1])),
           radioButtons("radio2", 
                       label = "Factor 1:",
                       choices = colnames(my_data[1:k])),
           radioButtons("radio3", 
                       label = "Factor 2:",
                       choices = colnames(my_data[2:k])),
          
    ),
        mainPanel(
          h4("Two-Way ANOVA"),
          dataTableOutput("two.way"),
          hr(),hr(),
          h4("Post Hoc Test for Multiple Comparisons (Tukey)"),
          dataTableOutput ("tukey1"),
          hr(),
          dataTableOutput ("tukey2"),
          hr(),
          dataTableOutput ("tukey3"),
          hr(),
          h4("Mean Plot with 95% Confidence Interval"),
          plotOutput("diff1"),
          hr(),
          h4("Homogeneity of Variances Test (Levene's)*"),
          textOutput("lev"),
          plotOutput("res"),
          hr(),
          h4("Normality Test (Shapiro-Wilk's)"),
          textOutput("shapiro"),
          plotOutput("qqres"),
          hr(),
          h6("*Izvorni Leveneov test homogenosti varijanci računa odstupanja rezultata entiteta od aritmetičke sredine. Brown i Forsythe (1974.) su predložili da se umjesto aritmetičke sredine koristi medijan jer je manje osjetljiv (bolja mjera centralne tendencije) u slučaju asimetričnih distribucija podataka.")
    )
),
server <- function(input, output, session) {

      selectedData1 <- reactive({
        my_data[, input$radio1]
  })
      selectedData2 <- reactive({   
        my_data[, input$radio2]
  })
      selectedData3 <- reactive({   
        my_data[, input$radio3]
  })
      
      output$two.way <- renderDataTable({
        Variables   <- selectedData1()
        Factor1     <- selectedData2()
        Factor2     <- selectedData3() 
        two.way <- aov(Variables ~ Factor1*Factor2, data = my_data)
        twanova <- summary(two.way)
        colnames(twanova[[1]]) <- c("df", "Sum Square","Mean Square", "F-value", "p-level")
        twanova[[1]] %>% DT::datatable (extensions = 'Buttons', options = list(dom = 'Bt',buttons = c('copy'))) %>% formatRound(c('Sum Square', 'Mean Square', 'F-value', 'p-level'), 3)
        })
      
      output$tukey1 <- renderDataTable({
        Variables   <- selectedData1()
        Factor1     <- selectedData2()
        Factor2     <- selectedData3() 
        two.way <- aov(Variables ~ Factor1*Factor2, data = my_data)  
        tuk <- TukeyHSD(two.way)
        colnames(tuk[[1]]) <- c("Mean Diff.", "Lower Bound","Upper Bound", "p-level")
        tuk[[1]]%>% DT::datatable (extensions = 'Buttons', options = list(pageLength = 100, dom = 'Bt',buttons = c('copy'))) %>% formatRound(c('Mean Diff.', 'Lower Bound', 'Upper Bound', 'p-level'), 3)
        })
      
      output$tukey2 <- renderDataTable({
        Variables   <- selectedData1()
        Factor1     <- selectedData2()
        Factor2     <- selectedData3() 
        two.way <- aov(Variables ~ Factor1*Factor2, data = my_data)  
        tuk <- TukeyHSD(two.way)
        colnames(tuk[[2]]) <- c("Mean Diff.", "Lower Bound","Upper Bound", "p-level")
        tuk[[2]]%>% DT::datatable (extensions = 'Buttons', options = list(pageLength = 500, dom = 'Bt',buttons = c('copy'))) %>% formatRound(c('Mean Diff.', 'Lower Bound', 'Upper Bound', 'p-level'), 3)
        })

      output$tukey3 <- renderDataTable({
        Variables   <- selectedData1()
        Factor1     <- selectedData2()
        Factor2     <- selectedData3() 
        two.way <- aov(Variables ~ Factor1*Factor2, data = my_data)  
        tuk <- TukeyHSD(two.way)
        colnames(tuk[[3]]) <- c("Mean Diff.", "Lower Bound","Upper Bound", "p-level")
        tuk[[3]]%>% DT::datatable (extensions = 'Buttons', options = list(pageLength = 1000, dom = 'Bt',buttons = c('copy'))) %>% formatRound(c('Mean Diff.', 'Lower Bound', 'Upper Bound', 'p-level'), 3)
        })
      
       output$diff1 <- renderPlot({
        Variables   <- selectedData1()
        Factor1     <- selectedData2()
        Factor2     <- selectedData3() 
        plotmeans(Variables~interaction(Factor2, Factor1, sep ="-"), data=my_data, col="red", barwidth=1,
          barcol="black",connect=FALSE, n.label=FALSE, xlab="")
    })      
      
       output$res <- renderPlot({
        Variables <- selectedData1()
        Factor1     <- selectedData2()
        Factor2     <- selectedData3() 
        res.aov <- aov(Variables ~ Factor1:Factor2, data = my_data)
        plot(res.aov,1)
    })   
     output$qqres <- renderPlot({
        Variables <- selectedData1()
        Factor1     <- selectedData2()
        Factor2     <- selectedData3() 
        res.aov <- aov(Variables ~ Factor1:Factor2, data = my_data)
        plot(res.aov,2)
    })   
     
      output$lev <- renderText({
        Variables <- selectedData1()
        Factor1     <- selectedData2()
        Factor2     <- selectedData3()
        lt <- leveneTest(Variables ~ Factor1:Factor2, data = my_data, center=mean)
        Fl <- round(lt$`F value`[1], digits = 3)
        pl <- round(lt$`Pr(>F)`[1], digits = 3)
        paste("F = ", Fl,", p = ", pl)
    })   
     
     output$shapiro <- renderText({
        Variables <- selectedData1()
        Factor1     <- selectedData2()
        Factor2     <- selectedData3()
        res.aov <- aov(Variables ~ Factor1:Factor2, data = my_data)
        res.residuals <- residuals(object = res.aov)
        sw <- shapiro.test(x = res.residuals)   
        W <- round(sw$statistic, digits = 3)
        p <- round(sw$p.value, digits = 3)
        paste("W = ", W,", p = ", p)
    })   
},
shinyApp(ui = ui, server = server)
)

```

