---
title: "One-way ANOVA"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    logo: R_logo.png
runtime: shiny
---

```{r}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)
library(psych)
library(car)
library(Rmisc)
library(gplots)
library(lsr)
library(RVAideMemoire)
library(ggthemes)

setwd("~/R-aplikacije/Datoteke/CSV")

data <- read.table(file.choose(),                  
                   header = TRUE,                      
                   dec = ",",                          
                   sep = ";",                          
                   stringsAsFactors = TRUE,
                   row.names = 1)

Factor <- data %>% select_if(is.factor)
Dependent <- data %>% select_if(is.numeric)

my_data <- cbind(Factor, Dependent)
vn <- variable.names(Dependent)
nn <- variable.names(Factor)
mm <- ncol(data)
m <- ncol(Dependent)
k <- ncol(Factor)
n <- nrow(data)
```

Data
=======================================================================
Column {data-width=1000}
-----------------------------------------------------------------------
### Data
```{r}
DT::datatable(data, style = 'bootstrap', 
              filter = 'top', 
              extensions = 'Buttons', 
              options = list(pageLength = n, dom = 'Brti', buttons = c('copy','csv', 'excel')))
```

Descriptive Statistics
=======================================================================
Column {data-width=1000}
-----------------------------------------------------------------------
### Descriptive Statistics & Normality Test
```{r}

shinyApp(

ui <- fluidPage(
        sidebarPanel(
          radioButtons("radio1", 
                       label = "Dependent Variables:",
                       choices = colnames(my_data[k+1:m])),
           radioButtons("radio2", 
                       label = "Independent Variables:",
                       choices = colnames(my_data[1:k])),
           sliderInput("bins",
                        "Broj razreda:",
                        min = 1,
                        max = 100,
                        value = 7)
          
        ),
        mainPanel(
          dataTableOutput ("des"),
          hr(),
          h5("Histogram"),
          plotOutput("histogram"),
          hr(),
          h5("Box and Whiskers plot"),
          plotOutput("box"),
          h5("QQ plot"),
          plotOutput("qq")
        )
),
server <- function(input, output, session) {

      selectedData1 <- reactive({
        my_data[, input$radio1]
  })
      selectedData2 <- reactive({   
        my_data[, input$radio2]
  })
      
       output$des <- renderDataTable({
        Variables <- selectedData1()
        Factor    <- selectedData2()
        des = summarySE(my_data,
              measurevar= input$radio1,
              groupvars=c(input$radio2))
        sw <- byf.shapiro(Variables~Factor,data=my_data)
        des <- cbind(des,sw$tab)
        colnames(des) <- c(input$radio2, "N", "MEAN", "SD", "SEM", "CI", "Shapiro-Wilk W", "P")
        des%>% DT::datatable (rownames = FALSE, 
                              style = 'bootstrap', 
                              extensions = 'Buttons', 
                              options = list(pageLength = 100, dom = 'Bt',buttons = c('copy'))) %>% 
        formatRound(c("MEAN", "SD", "SEM", "CI", "Shapiro-Wilk W", "P"), 3)
       })
       
      output$histogram <- renderPlot({
        Variables    <- selectedData1()
        Factor    <- selectedData2()
        ggplot(my_data, aes(x=Variables)) + 
        geom_histogram(bins=input$bins, color="#000000", fill="#4477AA") +
        labs(x= input$radio1, y = "Frequency") +
        facet_wrap(Factor)+
        theme_minimal()
  })
      
      output$box <- renderPlot({
        Variables  <- selectedData1()
        Groups     <- selectedData2()
        ggplot(my_data, aes(x=Groups, y=Variables, fill=Groups)) + 
        geom_boxplot(color="#000000",outlier.colour="red",outlier.shape=8, outlier.size=4) +
        stat_summary(fun=mean, geom="point", shape=16, size=2, color="#000000") +
        labs(x = input$radio2, y = input$radio1, fill = input$radio2) +
        theme_minimal() + scale_fill_ptol()
  })
      
       output$qq <- renderPlot({
        Variables    <- selectedData1()
        Factor    <- selectedData2()
        ggplot(my_data, aes(sample = Variables)) + 
        stat_qq_line(color="#000000",size=1) + 
        stat_qq(color="#4477AA", size=2) + 
        labs(x = input$radio2, y=input$radio1) +
        facet_wrap(Factor)+
        theme_minimal()
       }) 
  
},
shinyApp(ui = ui, server = server)
)
```

One-way ANOVA
=======================================================================
Column {data-width=1000}
-----------------------------------------------------------------------
### One-way ANOVA
```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
          radioButtons("radio1", 
                       label = "Dependent Variables:",
                       choices = colnames(my_data[k+1:m])),
           radioButtons("radio2", 
                       label = "Independent Variables:",
                       choices = colnames(my_data[1:k])),
        ),
        mainPanel(
          htmlOutput("anova"),
          hr(),
          h5("Post Hoc Test for Multiple Comparisons (Tukey)"),
          dataTableOutput ("tukey"),
          hr(),
          h5 ("Mean Plot with 95% Confidence Interval"),
          plotOutput("err")
        )
),

server <- function(input, output, session) {

      selectedData1 <- reactive({
        my_data[, input$radio1]
  })
      selectedData2 <- reactive({   
        my_data[, input$radio2]
  })
 
      output$anova <- renderText({
        Variables <- selectedData1()
        Factor     <- selectedData2()
        
        lt <- leveneTest (Variables ~ Factor, data = my_data, center = mean)
        Fl <- round(lt$`F value`[1], digits = 3)
        pl <- round(lt$`Pr(>F)`[1], digits = 3)
        at <- oneway.test(Variables ~ Factor, data = my_data, var.equal = TRUE)
        af <- oneway.test(Variables ~ Factor, data = my_data, var.equal = FALSE)
        ft <- round(at[["statistic"]], digits = 3)
        df1t <- round(at[["parameter"]][[1]], digits = 3)
        df2t <- round(at[["parameter"]][[2]], digits = 3)
        pt <- round(at[["p.value"]], digits = 3)
        ff <- round(af[["statistic"]], digits = 3)
        df1f <- round(af[["parameter"]][[1]], digits = 3)
        df2f <- round(af[["parameter"]][[2]], digits = 3)
        pf <- round(af[["p.value"]], digits = 3)
        
        if(pl>0.05){
          paste(
          "Levene's F = ", Fl, "</br>",
          "Levene's p = ", pl, "</br>",
          "Levene's test is not significant (p > .05)", "</br>",
          "Fisher's F = ", ft ,"</br>",
          "df1 =", df1t, "</br>",
          "df2 =", df2t, "</br>",
          "p = ", pt) 
          }
        else{
          paste(
          "Levene's F = ", Fl, "</br>",
          "Levene's p = ", pl, "</br>",
          "Levene's test is significant (p < .05), suggesting a violation of the assumption of equal variances", "</br>",
          "Welch's F = ", ff , "</br>",
          "df1 =", df1f, "</br>",
          "df2 =", df2f, "</br>",
          "p = ", pf) 
          }
    })  

      output$tukey <- renderDataTable({
        Variables <- selectedData1()
        Factor     <- selectedData2()
        tuk <- TukeyHSD(aov(Variables ~ Factor, data = my_data))
        colnames(tuk[[1]]) <- c("Mean Diff.", "Lower Bound","Upper Bound", "p-level")
        tuk[[1]]%>% DT::datatable (extensions = 'Buttons', 
                                   style = 'bootstrap', 
                                   options = list(pageLength = 100, dom = 'Bt',buttons = c('copy'))) %>% 
        formatRound(c('Mean Diff.', 'Lower Bound', 'Upper Bound', 'p-level'), 3)
    })
        
      output$err <- renderPlot({
        Variables <- selectedData1()
        Factor <-  selectedData2()
        plotmeans(Variables ~ Factor, 
                  data = my_data, 
                  col = "#D1495B",
                  barcol ="#4477AA", 
                  barwidth = 3,
                  connect = TRUE, 
                  n.label = FALSE, 
                  xlab = input$radio2, 
                  ylab = input$radio1,
                  )
    })
},
shinyApp(ui = ui, server = server)
)

```

