---
title: "Regression Analysis"
output: 
  flexdashboard::flex_dashboard:
    theme: cerulean
    logo: R_logo.png
runtime: shiny
---

```{r}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)
library(ggthemes)

setwd("~/R-aplikacije/Datoteke/CSV")

data <- read.table(file.choose(),                  
                   header = TRUE,                      
                   dec = ",",                          
                   sep = ";",                          
                   stringsAsFactors = TRUE,
                   row.names = 1)

my_data <- data %>% select_if(is.numeric)
mm <- ncol(my_data)
n <- nrow(my_data)
```

Data
=======================================================================
Column {data-width=1000}
-----------------------------------------------------------------------
### Data
```{r}
DT::datatable(data, style = 'bootstrap', 
              filter = 'top', 
              extensions = 'Buttons', 
              options = list(pageLength = n, dom = 'Brti', buttons = c('copy','csv', 'excel')))
```

Regression Analysis
=======================================================================
Column {data-width=1000}
-----------------------------------------------------------------------
### Regression Analysis
```{r}
shinyApp(

ui <- fluidPage(
        sidebarPanel(
          checkboxGroupInput("indep", "Independent Variables:",
                            names(my_data), selected = names(my_data[1:mm-1])),
          radioButtons("dep", "Dependent Variable:",
                       choices = colnames(my_data),
                       selected = names(my_data[mm]))
        ),
        mainPanel(
          tabsetPanel(
            tabPanel("Multiple Regression Results", br(),
                     htmlOutput("ro"),
                     hr(),
                     dataTableOutput("rez"),
                     hr(),
                     h5("Graph of Partial Coefficients of Determinations (P)"),
                     plotOutput("gro"),
                     hr(),
                     h5("Graph of Standardized Regression Coefficients, Partial Correlations and Correlations"),
                     plotOutput("gcoef")
                     ),
            tabPanel("Observed, Predicted & Residual Values", br(), dataTableOutput("dep"))
            )
        )
    ),

server <- function(input, output, session) {
    
     selectedData1 <- reactive({my_data[, input$indep]})
     selectedData2 <- reactive({my_data[, input$dep]})
      
      output$ro <- renderText({
        Independent <- selectedData1()
        Dependent <- selectedData2()
        
        X <- as.matrix(Independent)
        Y <- as.matrix(Dependent)
        m <- ncol(X)+1
        
        B0 <- rep.int(1, n)
        Xi <- cbind(B0, X)
        XTXi <- t(Xi) %*% Xi
        XTY <- t(Xi) %*% Y
        b <- solve(XTXi) %*% XTY
        Yp <- Xi %*% b 
        e <- Y - Yp
        se <- round(sqrt(sum(e*e)/(n-m)), digits = 2)
        pss <- sum((Yp-mean(Yp))**2)
        rss <- sum((e-mean(e))**2)
        ro2 <- pss/(pss+rss)
        ro <- round(sqrt(ro2), digits = 2)
        dfp <- m-1
        dfe <- n-m
        Fval <- (pss/dfp)/(rss/dfe)
        pf <- pf(Fval, dfp, dfe, lower.tail = FALSE)
                
       paste("RO =", round(ro, digits = 3), 
             "; RO2 =", round(ro2, digits = 3), 
             "; SEE =", round(se, digits = 2), 
             "; F-value =", round(Fval, digits = 2), 
             "p-value  =", round(pf, digits = 4))
      })
      
      output$rez <- renderDataTable({
        Independent <- selectedData1()
        Dependent <- selectedData2()
        
        X <- as.matrix(Independent)
        Y <- as.matrix(Dependent)
        XY <- cbind(X,Y)
        m <- ncol(XY)
        
        Z <- scale(X)
        K <- scale(Y)
        ZK <- round(cbind(Z,K), digits = 2)
        Rxy <- cor(XY)
        R <- cor(X)
        B0 <- rep.int(1, n)
        Xi <- cbind(B0,X)
        XTXi <- t(Xi) %*% Xi
        XTY <- t(Xi) %*% Y
        b <- solve(XTXi) %*% XTY
        r1 <- (t(Z) %*% K)/(n-1)
        r <- rbind(0, r1)
        beta1 <- solve(R) %*% r1
        beta <- rbind(0,beta1)
        S2 <- 1/diag(solve(R))
        s2 <- data.frame(S2)
        s2<- rbind(0,s2)
        S2xy <- 1/diag(solve(Rxy))
        Sxy <- sqrt(S2xy)
        Pr <- diag(Sxy) %*% solve(Rxy) %*% diag(Sxy)
        pr <- (Pr[,m]*-1)
        pr <- pr[1:m-1]
        pr <- data.frame(pr)
        pr <- rbind(0,pr)
        p <- beta*r
        Yp <- Xi %*% b 
        e <- Y - Yp
        se <- round(sqrt(sum(e*e)/(n-m)), digits = 2)
        wjj <- solve(XTXi)
        diagwjj <- diag(wjj)
        seb <- se*sqrt(diagwjj)
        tb <- abs(b/seb)
        df <- n-m
        pval <- c()
        for (a in 0:m) {pval[a] <- c(2*(pt(abs(tb[a,1]), df, lower.tail = FALSE)))}
        tb <- data.frame(tb)
        pval <- data.frame(pval)
        
        rez <- cbind(b, seb, beta, pr, r, p, s2, tb, pval)
        colnames(rez) <- c("B","SE(B)", "Beta", "Part_R", "R","P", "Tolerance", "t", "p")
        rez %>% DT::datatable (
                     style = 'bootstrap', 
                     extensions = 'Buttons', 
                     options = list(pageLength = m, dom = 'Bt',buttons = c('copy'))) %>% 
                     formatRound(colnames(rez), digits=3) %>% 
                     formatStyle('p', color = styleInterval(c(0.05), c('red', 'black')))
      })

      output$gro <- renderPlot({
        Independent <- selectedData1()
        Dependent <- selectedData2()
        
        X <- as.matrix(Independent)
        Y <- as.matrix(Dependent)
        XY <- cbind(X,Y)
        Variables <- colnames(X)
      
        m <- ncol(XY)
        Z <- scale(X)
        K <- scale(Y)
        Rxy <- cor(XY)
        R <- cor(X)
        r1 <- (t(Z) %*% K)/(n-1)
        r <- rbind(0, r1)
        beta1 <- solve(R) %*% r1
        beta <- rbind(0,beta1)
        S2xy <- 1/diag(solve(Rxy))
        Sxy <- sqrt(S2xy)
        Pr <- diag(Sxy) %*% solve(Rxy) %*% diag(Sxy)
        pr <- (Pr[,m]*-1)
        pr <- pr[1:m-1]
        pr <- data.frame(pr)
        pr <- rbind(0,pr)
        p <- beta*r

      pgg <- round(p[2:m], digits = 2)
      pggdf <- cbind.data.frame(Variables,pgg)

      ggplot(pggdf, aes(x= Variables, y = pgg, fill = Variables)) +
            geom_bar(stat = "identity", color = "white") +
            labs(x ="Variables",y ="value",fill ="",title= "") +
            theme_minimal() + scale_fill_ptol()
        
        })
      
       output$gcoef <- renderPlot({
        Independent <- selectedData1()
        Dependent <- selectedData2()
        
        X <- as.matrix(Independent)
        Y <- as.matrix(Dependent)
        XY <- cbind(X,Y)
        Variables <- colnames(X)
        m <- ncol(XY)
        
        Z <- scale(X)
        K <- scale(Y)
        Rxy <- cor(XY)
        R <- cor(X)
        r1 <- (t(Z) %*% K)/(n-1)
        r <- rbind(0, r1)
        beta1 <- solve(R) %*% r1
        beta <- rbind(0,beta1)
        S2xy <- 1/diag(solve(Rxy))
        Sxy <- sqrt(S2xy)
        Pr <- diag(Sxy) %*% solve(Rxy) %*% diag(Sxy)
        pr <- (Pr[,m]*-1)
        pr <- pr[1:m-1]
        pr <- data.frame(pr)
        pr <- rbind(0,pr)
      
        koef <- cbind(beta, pr, r)
        colnames(koef) <- c("Beta", "Part_R", "R")
        

        grez <- cbind.data.frame(Variables,koef$Beta[2:m], koef$Part_R[2:m], koef$R[2:m])
        ncoef <- c("BETA", "PART-R", "R")
        coef <- rep(ncoef, each=m-1)
        var <- rep(Variables, times=3)
        val <- c()
        for (a in 2:4) {val <- c(val,grez[,a])}
        ggrez <- data_frame(coef,var,val)
        
        ggplot(ggrez, aes(x=var, y = val, fill= coef)) +
                 geom_bar(position="dodge",stat = "identity")+
                 labs(x ="Variables",y ="value",fill ="",title= "")+
                 theme_minimal() + scale_fill_ptol()

})
      
      output$dep <- renderDataTable({
        Independent <- selectedData1()
        Dependent <- selectedData2()
        
        X <- as.matrix(Independent)
        Y <- as.matrix(Dependent)
        B0 <- rep.int(1, n)
        Xi <- cbind(B0,X)
        XTXi <- t(Xi) %*% Xi
        XTY <- t(Xi) %*% Y
        b <- solve(XTXi) %*% XTY
        Yp <- Xi %*% b 
        e <- Y - Yp
        dep <- cbind(Y, Yp, e)
        colnames(dep) <- c("Observed Value","Predicted Value", "Residual")
        
        dep %>% DT::datatable (style = 'bootstrap', 
                     extensions = 'Buttons', 
                     options = list(pageLength = n, dom = 'Bt',buttons = c('copy'))) %>% 
                     formatRound(colnames(dep), digits=3) 
      })
},
shinyApp(ui = ui, server = server)
)
```
